services:
  db:
    image: postgres
    container_name: cinema-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
